import logging
from pathlib import Path

DEFAULT_LOGGING_DEBUG_LEVEL = logging.DEBUG

DELETE_TEMP_FOLDER_ON_STARTUP = True
TEMP_FOLDER_NAME = "M0WUT_tools"


PROJECT_TRACKER_REPO_OWNER = "M0WUT"
PROJECT_TRACKER_REPO_NAME = "project-tracker"
PROJECT_TRACKER_JSON_PATH = Path("projects.json")

PROJECT_JSON_PATH = Path("project_structure.json")

GITHUB_PAGES_DEPLOYMENT_WORKFLOW_NAME = "main.yml"

KICAD_TEMPLATE_REPO_OWNER = "M0WUT"
KICAD_TEMPLATE_REPO_NAME = "p0002-pcb-001_kicad-template-pcb"
KICAD_TEMPLATE_STR_TO_REPLACE = "P0002-PCB-001"

KICAD_RELEASER_REPO_OWNER = "M0WUT"
KICAD_RELEASER_REPO_NAME = "kicad_releaser"
